# Generated by Django 3.2.8 on 2021-10-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Email')),
                ('tipoNegocio', models.CharField(max_length=100, unique=True, verbose_name='TipoNegocio')),
                ('descricao', models.CharField(max_length=100, unique=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Contract Form',
            },
        ),
    ]
