# Generated by Django 3.2.8 on 2021-11-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractform',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='contractform',
            name='tipoNegocio',
            field=models.CharField(max_length=100, verbose_name='TipoNegocio'),
        ),
    ]
